// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { createMiddleware } from '@michalsy/aiko-webapp-core/middleware'

export const middleware = createMiddleware({
  protectedPaths: ["/dashboard","/api"],
})

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
}
